@startuml
[*] --> НеАктивирована : Бомба не активирована

НеАктивирована --> АктивацияНевозможна : Бомба уже активирована
АктивацияНевозможна --> НеАктивирована : Возврат к исходному состоянию

НеАктивирована --> АктивацияВозможна : Условие активации выполнено
АктивацияВозможна --> Активация : Активация бомбы

Активация --> Анимация : Запуск анимации
Анимация --> Активация : Продолжение анимации
Анимация --> Завершение : Завершение анимации

Завершение --> [*] : Завершение процесса
@enduml
