@startuml
(*) --> "Пользователь нажимает кнопку установки бомбы"
if "Бомба уже активирована?" then
  -->[да] "Отмена установки бомбы"
else
  -->[нет] "Получить текущее положение бомбы"
  --> "Сравнить текущее положение бомбы с предыдущим"
  if "Бомба не передвигалась?" then
    -->[да] "Проверить время установки бомбы"
    if "Прошло достаточное время?" then
      -->[да] "Установка бомбы"
      --> "Запуск анимации установки"
      --> (*)
    else
      -->[нет] "Обновление времени установки"
      --> (*)
    endif
  else
    -->[нет] "Обновить стартовое время и позицию"
    --> (*)
  endif
endif
@enduml
