@startuml
[*] --> НеНачато

state НеНачато {
  [*] --> НачальноеСостояние
  НачальноеСостояние --> Начато : ПолученаКомандаНачала
}

state Начато {
  [*] --> Исследование

  state Исследование {
    [*] --> ПроверкаСоседнихЯчеек

    state ПроверкаСоседнихЯчеек {
      [*] --> ПроверкаВерхнейЯчейки
      ПроверкаВерхнейЯчейки --> ПроверкаПравойЯчейки
      ПроверкаПравойЯчейки --> ПроверкаНижнейЯчейки
      ПроверкаНижнейЯчейки --> ПроверкаЛевойЯчейки
      ПроверкаЛевойЯчейки --> ПроверкаЗавершенияИлиТупика
    }

    state ПроверкаЗавершенияИлиТупика {
      [*] --> НетДоступныхХодов
      НетДоступныхХодов --> ИсследованиеЗавершено : НетДоступныхХодов
      ПроверкаЗавершенияИлиТупика --> СделатьХод : ДоступныеХодыЕсть
    }

    state СделатьХод {
      [*] --> ХодСовершён
      ХодСовершён --> ОбновитьГрафИСтены
      ОбновитьГрафИСтены --> ПроверкаСоседнихЯчеек
    }

    state ИсследованиеЗавершено {
      [*] --> Завершено
    }
  }
}
@enduml
