@startuml
[*] --> Непосещена : (w, h) не посещена
Непосещена --> Посещена : Посетить (w, h)
Посещена --> ЕстьПути : Есть варианты движения
Посещена --> НетПутей : Нет вариантов движения
НетПутей --> Посещена : Возврат
НетПутей --> [*] : Завершение
ЕстьПути --> СделатьВыбор : Выбрать направление
СделатьВыбор --> Непосещена : Двигаться
СделатьВыбор --> ЕстьПути : Продолжить
СделатьВыбор --> НетПутей : Тупик
@enduml