@startuml
start
:Пользователь хочет купить улучшение;
if (достаточно монет?) then (да)
  :Уменьшить количество монет на цену улучшения;
  :В зависимости от выбранного улучшения
  улучшить одну из способностей героя или его оружия;
else (нет)
endif
stop
@enduml