@startuml
[*] --> Начало : Начало процесса

Начало --> ПоискПути : Инициализация начальной вершины и очереди
ПоискПути --> ПроверкаГлубины : Проверка на достижение максимальной глубины
ПроверкаГлубины --> ПоискПути : Продолжение поиска пути
ПроверкаГлубины --> ПоискЗавершен : Достигнута максимальная глубина
ПоискПути --> ПроверкаНайденного : Проверка на нахождение целевой вершины
ПоискЗавершен --> [*] : Завершение процесса

ПроверкаНайденного --> ПоискПути : Продолжение поиска пути
ПроверкаНайденного --> СобираниеПути : Найден путь до целевой вершины

СобираниеПути --> ПроверкаКонечной : Проверка достижения начальной вершины
СобираниеПути --> СобираниеПути : Сбор пути
ПроверкаКонечной --> [*] : Завершение сбора пути
@enduml
