@startuml
scale 350 width
[*] --> НеНачато

state НеНачато {
  [*] --> Готов
  Готов --> Обработка : ЗапросНавигации
}

state Обработка {
  [*] --> ПоискПути

  state ПоискПути {
    [*] --> ПроверкаСледующейПозиции

    state ПроверкаСледующейПозиции {
      [*] --> ПроверкаВозможныхХодов
      ПроверкаВозможныхХодов --> ПроверкаМаксимальнойГлубиныИлиЦели : ВозможныеХодыНайдены
    }

    state ПроверкаМаксимальнойГлубиныИлиЦели {
      [*] --> ПутьНайден
      ПутьНайден --> ПостроениеПути : ДостигнутаЦель
      ПутьНайден --> НеПутьНайден : ДостигнутаМаксимальнаяГлубина
    }

    state ПостроениеПути {
      [*] --> ПутьПостроен
    }

    state НеПутьНайден {
      [*] --> ПутьНеНайден
    }
  }
}
@enduml
