@startuml
[*] --> НеСтрельба

state НеСтрельба {
  [*] --> Готов
  Готов --> Стрельба : ЗапросНаВыстрел
}

state Стрельба {
  [*] --> ПринятиеРешенияОСтрельбе

  state ПринятиеРешенияОСтрельбе {
    [*] --> РешениеОСтрельбе
    РешениеОСтрельбе --> Прицеливание : МожноСтрелять
    РешениеОСтрельбе --> Перезарядка : НетПатронов

    state Прицеливание {
      [*] --> ОдиночныйВыстрел
      ОдиночныйВыстрел --> Стрельба : ВыбранОдиночныйВыстрел
    }

    state Перезарядка {
      [*] --> ЗадержкаПерезарядки
      ЗадержкаПерезарядки --> Готов : ПерезарядкаЗавершена
    }
  }

  state Стрельба {
    [*] --> ПодготовкаПули

    state ПодготовкаПули {
      [*] --> ПрицельныйВыстрел
      ПрицельныйВыстрел --> ВыстрелПули : ПрицеливаниеЗавершено
    }

    state ВыстрелПули {
      [*] --> ЗавершениеСтрельбы
      ЗавершениеСтрельбы --> Готов : ЗавершениеАнимацииСтрельбы
    }
  }
}
@enduml
