name: Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libsfml-dev lcov cmake

    - name: Setup GoogleTest
      run: |
        cd /usr/src/googletest
        sudo cmake .
        sudo make
        sudo cp lib/libgtest*.a /usr/lib

    - name: Build project
      run: make -C tests

    - name: Run tests
      run: |
        cd tests
        ./test_suite

    - name: Generate coverage info
      run: |
        cd tests
        lcov --capture --directory . --output-file coverage.info

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: tests/coverage.info
        flags: unittests
        name: codecov-umbrella
