name: Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libsfml-dev lcov cmake

    - name: Install Google Test
      run: |
        sudo apt-get install -y libgtest-dev
        cd /usr/src/googletest
        sudo cmake .
        sudo make
        sudo cp lib/*.a /usr/local/lib/

    - name: Compile and run tests
      run: |
        cd tests
        make
        ./test_suite

    - name: Generate coverage report
      run: |
        lcov --capture --directory . --output-file coverage.info
        lcov --remove coverage.info '/usr/*' 'tests/*' --output-file coverage.info
        lcov --list coverage.info

    - name: Install gcovr
      run: |
        pip install gcovr==5.0

    - name: Upload coverage to Coveralls
      run: |
        gcovr -r . --xml-pretty -o coverage.xml
        echo "Uploading coverage to Coveralls"
        curl --request POST --form json_file=@coverage.xml https://coveralls.io/api/v1/jobs
