name: CI/CD GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  gtest-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 

      - name: Install SFML dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libsfml-dev

      - name: Build and run tests
        run: |
          make -C tests
          ./tests/runTests

      - name: Install gcovr
        run: |
          pip install gcovr

      - name: Generate coverage report
        run: |
          gcovr --root . --exclude tests --xml > coverage.xml

  coveralls:
    needs: gtest-tests
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.xml
